AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/**/*'

Style/AccessModifierDeclarations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - db/migrate/*.rb
