version: 2

references:
  install_pg_tools: &install_pg_tools
    run:
      name: Install pg tools
      command: |
        echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' | sudo tee /etc/apt/sources.list.d/pgdg.list > /dev/null
        wget --no-check-certificate -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O- | sudo -u root apt-key add -
        sudo apt-get update
        sudo apt-get install postgresql-client-10
  install_bundler: &install_bundler
    run:
      name: Install latest Bundler
      command: gem install bundler

  restore_cache: &restore_cache
    restore_cache:
      keys:
      - v1-dependencies-{{ .BuildNum }}

  install_dependencies: &install_dependencies
    run:
      name: install dependencies
      command: bundle install --path vendor/bundle

  save_cache: &save_cache
    save_cache:
      paths:
        - ./vendor/bundle
      key: v1-dependencies-{{ .BuildNum }}

  setup_database: &setup_database
    run:
      name: Database setup
      command: bundle exec rake db:migrate

defaults: &defaults
  docker:
    - image: circleci/ruby:2.5.1
      environment:
        - RAILS_ENV: test
        - BUNDLE_JOBS: 3
        - BUNDLE_RETRY: 3
        - PG_HOST: localhost
        - PG_USER: circleci
        - DATABASE_URL: postgresql://circleci@localhost/sc_test
    - image: circleci/postgres:10.1
      environment:
        - POSTGRES_DB: sc_test
        - POSTGRES_USER: circleci
    - image: redis:alpine

  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    steps:
      - add_ssh_keys
      - checkout
      - *install_pg_tools
      - *install_bundler
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - *setup_database
      - run:
          name: Run rubocop offences check
          command: bundle exec rubocop .
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  build:
    jobs:
      - build
